### PR TITLE
Add async-actions

### PR DESCRIPTION
**Pull request by ChrisPenner**
Adds `doAsync` and switches the event-listener system to use the same unifying interface.

There're some really interesting ideas using `Cont` and `Free` here: https://github.com/ChrisPenner/rasa/issues/11#issuecomment-269878023

I'd still definitely like to pursue these, but this cleaned up the event system as it was anyways, so I went ahead with it for now. If me or anyone else can eventually figure out how to do the cleaner syntax presented in https://github.com/ChrisPenner/rasa/issues/11#issuecomment-269878023 then we'll integrate it later.

Let me know what you think @mitchellwrosen, as I said, I'd still love to work towards the cleaner version you presented, feel free to hack on this a bit if you have ideas for how to implement it! In the mean-time I'd love your feedback on this change.

### CODE REVIEW

**Comment by ChrisPenner** [comment]
Seems like this broke the haddock build somehow... anyone know tips on how to find out where it's choking?

**Comment by mitchellwrosen** [comment]
Ah, I see how this all fits together now. So, my comments in #11 were a bit misguided as I didn't really look at the event dispatching machinery. However, there are still some problems with this approach (namely, async events block the main event loop until the first one returns).

**Comment by ChrisPenner** [comment]
It's correct that the event loop blocks until one of the async calls complete, however this isn't actually a problem; The only way changes can happen in the editor is to process an event, and the only way to listen for events is via async actions, if it's stalled on the `waitAny` call it's because absolutely nothing is happening. All events must go through the async machinery, and therefore we're not blocking the event loop from doing anything else important.

Does that make sense? I've run this code and it works as expected 😁

**Comment by mitchellwrosen** [comment]
Oh. Are you spawning a new thread for every key press now, though?

**Comment by ChrisPenner** [comment]
Hrmm, I suppose we would be spawning a thread per event yes! Not really sure of a way around that, I suppose we could take a look at some of the Pipes libraries, they may provide something for this.

I'm not terribly concerned about it for the time being though, it's only spawning Haskell threads, not OS threads ([referenced here](https://hackage.haskell.org/package/base-4.9.0.0/docs/Control-Concurrent.html#g:11)); haskell threads are extremely efficient and lightweight. There's definitely a possibility that this won't scale up as we move forwards, but I'd rather not optimize prematurely for something like that unless it provides a cleaner API for extensions.

**Comment by mitchellwrosen** [comment]
Yeah, I meant a Haskell thread, and I'm also all for avoiding premature optimization, but spawning a thread per key press does seem excessive...

In the meantime I'll play around with the code and see if I can more properly explain what I'm talking about with Free and friends.

**Comment by ChrisPenner** [comment]
> spawning a thread per key press does seem excessive...

Agreed! If you can figure something out I'm all ears!

**Comment by ChrisPenner** [comment]
I'm going to merge this through for now, we can keep talking on that issue and make more changes later if we come up with something.

**Pull request merged**
